# Generated by Django 5.1.2 on 2024-12-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
    ]
