# Generated by Django 5.2.5 on 2025-08-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickFood', '0003_pantry_remove_recipe_ingredients_delete_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255)),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('total_time', models.IntegerField()),
                ('servings', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('image', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField()),
                ('url', models.URLField()),
                ('cuisine_path', models.CharField(blank=True, max_length=255, null=True)),
                ('nutrition', models.JSONField(blank=True, null=True)),
                ('timing', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
